using System.Text.Json;
using System.Text.Json.Serialization;

namespace WindowsCanvas.Contracts;

/// <summary>
/// Serialization for the Windows surface. It is deliberately a separate context from the Mobile
/// one: the two products share a host process but not a payload vocabulary, and Native AOT needs
/// every type it serializes to be rooted by the generator rather than discovered by reflection.
/// </summary>
[JsonSourceGenerationOptions(
	PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
	DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
	WriteIndented = false)]
[JsonSerializable(typeof(WindowsApiError))]
[JsonSerializable(typeof(WindowsOperationResult))]
[JsonSerializable(typeof(WindowsHelperEnvelope))]
[JsonSerializable(typeof(WindowsHelperErrorDetail))]
[JsonSerializable(typeof(WindowsHelperCapabilities))]
[JsonSerializable(typeof(WindowsHelperCatalog))]
[JsonSerializable(typeof(WindowsHelperCatalogEntry))]
[JsonSerializable(typeof(WindowsHelperCatalogEntry[]))]
[JsonSerializable(typeof(WindowsHelperCatalogSource))]
[JsonSerializable(typeof(WindowsHelperCatalogSource[]))]
[JsonSerializable(typeof(WindowsHelperWindow))]
[JsonSerializable(typeof(WindowsHelperWindow[]))]
[JsonSerializable(typeof(WindowsHelperWindowList))]
[JsonSerializable(typeof(WindowsHelperLaunch))]
[JsonSerializable(typeof(WindowsHelperSession))]
[JsonSerializable(typeof(WindowsPreflight))]
[JsonSerializable(typeof(WindowsFeatureState))]
[JsonSerializable(typeof(WindowsFeatureState[]))]
[JsonSerializable(typeof(WindowsSessionEnvironment))]
[JsonSerializable(typeof(WindowsCatalogEntry))]
[JsonSerializable(typeof(WindowsCatalogEntry[]))]
[JsonSerializable(typeof(WindowsLaunchProvenance))]
[JsonSerializable(typeof(WindowsLaunchProvenance[]))]
[JsonSerializable(typeof(WindowsCatalogQuery))]
[JsonSerializable(typeof(WindowsCatalogResult))]
[JsonSerializable(typeof(WindowsCatalogSourceState))]
[JsonSerializable(typeof(WindowsCatalogSourceState[]))]
[JsonSerializable(typeof(WindowsWindowCandidate))]
[JsonSerializable(typeof(WindowsWindowCandidate[]))]
[JsonSerializable(typeof(WindowsWindowCandidateList))]
[JsonSerializable(typeof(WindowsWindowDiagnostics))]
[JsonSerializable(typeof(WindowsWindowBounds))]
[JsonSerializable(typeof(WindowsAuthorizedWindow))]
[JsonSerializable(typeof(WindowsAuthorizedWindow[]))]
[JsonSerializable(typeof(WindowsAuthorizedWindowList))]
[JsonSerializable(typeof(WindowsAppSession))]
[JsonSerializable(typeof(WindowsAppSession[]))]
[JsonSerializable(typeof(WindowsAppSelection))]
[JsonSerializable(typeof(WindowsProcessIdentity))]
[JsonSerializable(typeof(WindowsProcessIdentity[]))]
[JsonSerializable(typeof(WindowsCatalogLaunchRequest))]
[JsonSerializable(typeof(WindowsExecutableLaunchRequest))]
[JsonSerializable(typeof(WindowsAttachRequest))]
[JsonSerializable(typeof(WindowsSelectWindowRequest))]
[JsonSerializable(typeof(WindowsWindowActionRequest))]
[JsonSerializable(typeof(WindowsUiPhysicalPixelRect))]
[JsonSerializable(typeof(WindowsUiProperties))]
[JsonSerializable(typeof(WindowsUiSupportedActions))]
[JsonSerializable(typeof(WindowsUiElement))]
[JsonSerializable(typeof(WindowsUiElement[]))]
[JsonSerializable(typeof(WindowsUiOperationMetadata))]
[JsonSerializable(typeof(WindowsUiSnapshotRequest))]
[JsonSerializable(typeof(WindowsUiSnapshot))]
[JsonSerializable(typeof(WindowsUiSelector))]
[JsonSerializable(typeof(WindowsUiSelector[]))]
[JsonSerializable(typeof(WindowsUiQuery))]
[JsonSerializable(typeof(WindowsUiMatch))]
[JsonSerializable(typeof(WindowsUiMatch[]))]
[JsonSerializable(typeof(WindowsUiFindResult))]
[JsonSerializable(typeof(WindowsUiScrollRequest))]
[JsonSerializable(typeof(WindowsUiActionRequest))]
[JsonSerializable(typeof(WindowsUiActionResult))]
[JsonSerializable(typeof(WindowsUiWaitRequest))]
[JsonSerializable(typeof(WindowsUiWaitResult))]
[JsonSerializable(typeof(WindowsHelperUiSnapshot))]
[JsonSerializable(typeof(WindowsHelperUiFind))]
[JsonSerializable(typeof(WindowsHelperUiAction))]
[JsonSerializable(typeof(WindowsHelperUiWait))]
[JsonSerializable(typeof(WindowsCapturePoint))]
[JsonSerializable(typeof(WindowsCaptureGeometry))]
[JsonSerializable(typeof(WindowsCaptureCapabilities))]
[JsonSerializable(typeof(WindowsScreenshotRequest))]
[JsonSerializable(typeof(WindowsScreenshotDescriptor))]
[JsonSerializable(typeof(WindowsScreenshotArtifact))]
[JsonSerializable(typeof(WindowsStreamRequest))]
[JsonSerializable(typeof(WindowsStreamDescriptor))]
[JsonSerializable(typeof(WindowsStreamEnd))]
[JsonSerializable(typeof(WindowsHelperCapture))]
[JsonSerializable(typeof(WindowsInputPoint))]
[JsonSerializable(typeof(WindowsInputFrame))]
[JsonSerializable(typeof(WindowsClickRequest))]
[JsonSerializable(typeof(WindowsPointerRequest))]
[JsonSerializable(typeof(WindowsDragRequest))]
[JsonSerializable(typeof(WindowsWheelRequest))]
[JsonSerializable(typeof(WindowsKeyRequest))]
[JsonSerializable(typeof(WindowsTypeTextRequest))]
[JsonSerializable(typeof(WindowsInputResult))]
[JsonSerializable(typeof(JsonElement))]
public partial class WindowsJsonContext : JsonSerializerContext;
